presubmits:
  GoogleCloudPlatform/gke-networking-api:
  - name: pull-gke-networking-api-test
    branches:
    - main
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241021-d3a4913879-master
        command:
        - ./hack/verify-codegen.sh
